-- BudgetControl schema. Requires PostgreSQL 15+ (NULLS NOT DISTINCT).
-- Safe to run repeatedly: every statement is idempotent.

CREATE TABLE IF NOT EXISTS users (
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    email         TEXT        NOT NULL,
    password_hash TEXT        NOT NULL,
    created_at    TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE UNIQUE INDEX IF NOT EXISTS users_email_lower_key ON users (lower(email));

-- user_id NULL = default (shared) category
CREATE TABLE IF NOT EXISTS categories (
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id    BIGINT REFERENCES users (id),
    name       TEXT NOT NULL,
    color      TEXT NOT NULL CHECK (color ~ '^#[0-9A-Fa-f]{6}$'),
    created_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE UNIQUE INDEX IF NOT EXISTS categories_user_name_key
    ON categories (user_id, lower(name)) NULLS NOT DISTINCT;

-- Amounts are whole tenge (KZT).
CREATE TABLE IF NOT EXISTS expenses (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id     BIGINT      NOT NULL REFERENCES users (id),
    category_id BIGINT      NOT NULL REFERENCES categories (id),
    amount      BIGINT      NOT NULL CHECK (amount > 0),
    date        DATE        NOT NULL,
    note        TEXT,
    created_at  TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS expenses_user_date_idx ON expenses (user_id, date);

-- category_id NULL = overall monthly budget; month is always the 1st.
CREATE TABLE IF NOT EXISTS budgets (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id     BIGINT      NOT NULL REFERENCES users (id),
    category_id BIGINT      REFERENCES categories (id) ON DELETE CASCADE,
    amount      BIGINT      NOT NULL CHECK (amount > 0),
    month       DATE        NOT NULL CHECK (month = date_trunc('month', month)::date),
    created_at  TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE UNIQUE INDEX IF NOT EXISTS budgets_user_category_month_key
    ON budgets (user_id, category_id, month) NULLS NOT DISTINCT;

-- Default categories (user_id NULL); the unique index makes re-runs a no-op.
INSERT INTO categories (user_id, name, color) VALUES
    (NULL, 'Food',          '#F59E0B'),
    (NULL, 'Transport',     '#3B82F6'),
    (NULL, 'Housing',       '#10B981'),
    (NULL, 'Entertainment', '#8B5CF6'),
    (NULL, 'Health',        '#EF4444'),
    (NULL, 'Other',         '#6B7280')
ON CONFLICT DO NOTHING;
